### ISSUE TITLE
Integrate QA blur test in cobweb app

### ISSUE THREAD

**Issue by gmh04** [edina/fieldtrip-cobweb-project#101]
Perform blur test on photo taken if defined in survey

Options:

1) simply record in observation that image did not pass threshold
2) prompt user to retake photo

see https://github.com/cobweb-eu/cordova-cobweb-qa/issues/1 for work on cordova plugin.

**Comment by xmichael** [comment]
(2) without recording anything is probably best as the (1) seems more appropriate for server-side QA (or for future work).

**Comment by gmh04** [comment]
Probably best if @panterz does the Survey Designer change?

Once implemented in form, remove comment here: https://github.com/edina/fieldtrip-open/blob/master/src/www/js/records.js#L1689-L1695

**Comment by panterz** [comment]
is this tested and working?
