### ISSUE TITLE
fab install_project is not working

### ISSUE THREAD

**Issue by panterz** [edina/fieldtrip-cobweb-project#103]
I cannot install the new cobweb-qa plugin because of the submodule.

**Comment by panterz** [comment]
Related to #101

**Comment by gmh04** [comment]
I can't see a way of adding a git repo cordova plugin with a submodule.  I was installing this from my locally repo (using fab install_cordova_plugin) hence the reason why I didn't see this.  We can

1) simply add a jar file from a qa library build to the cordova plugin
2) modify install_project to clone the repo locally, do git submodule init before adding the plugin. we would need a way of identifying plugins with submodules in project.json (perhaps have a third plugin section)

Neither solution is particularly great, but 1. is the simplest.

**Comment by xmichael** [comment]
Given that this is all about just one file (BlurCheckRunnable.java) then in the case of solution (1) I would just add that particular file instead of the whole binary jar file.
