### ISSUE TITLE
FTOpen: the app should be generating names for the records

### ISSUE THREAD

**Issue by panterz** [edina/fieldtrip-cobweb-project#108]
when the user hasn't defined which field to be the one that will name the record. 
This is defined like this:

https://github.com/edina/survey-designer/blob/a8b7884e55eda256d34f9a6ef1ef37c397692940/test/survey.json#L6-L8

If there is no such a thing the app should go and create unique names e.g. survey name-date

It also need to b hidden when the form appears to the user.

**Comment by gmh04** [comment]
Some clarification from discussion with panos:

1) if multiple values in recordLayout.headers, use first element
2) if recordLayout.headers is defined the default value will be json.fields[].properties.prefix

**Comment by gmh04** [comment]
An attribute will be added to field that will be used as record title, e.g:

<input name="form-test" id="fieldcontain-text-1" **data-title="true"** ... /
