### ISSUE TITLE
fieldtrip-sync: should be using new pcapi.js

### ISSUE THREAD

**Issue by panterz** [edina/fieldtrip-cobweb-project#111]
In addition to this make sure that no fs requests are being called for any of the plugins.

**Comment by panterz** [comment]
You need to install the new pcapi.

**Comment by gmh04** [comment]
Error from decision tree opening form:

03-11 14:05:47.639 I/chromium( 7941): [INFO:CONSOLE(1076)] "processMessage failed: Stack: Error: Syntax error, unrecognized expression: {"geoms":["point"],"recordLayout":{"headers":[]},"fields":[{"id":"image-1","type":"image","required":false,"persistent":false,"properties":{"multi-image":false,"los":false,"blur":"0"},"label":"This is a label"}],"title":"dog Protokoll"}
03-11 14:05:47.639 I/chromium( 7941):     at Function.ga.error (file:///android_asset/www/js/ext/jquery.js:2:12731)
03-11 14:05:47.639 I/chromium( 7941):     at ga.tokenize (file:///android_asset/www/js/ext/jquery.js:2:18658)
03-11 14:05:47.639 I/chromium( 7941):     at ga.select (file:///android_asset/www/js/ext/jquery.js:2:21386)
03-11 14:05:47.639 I/chromium( 7941):     at Function.ga (file:///android_asset/www/js/ext/jquery.js:2:7364)
03-11 14:05:47.639 I/chromium( 7941):     at Function.a.find (file:///android_asset/www/js/ext/jquery-mobile.js:3:16131)
03-11 14:05:47.639 I/chromium( 7941):     at m.fn.extend.find (file:///android_asset/www/js/ext/jquery.js:2:23660)
03-11 14:05:47.639 I/chromium( 7941):     at m.fn.init (file:///android_asset/www/js/ext/jquery.js:2:24231)
03-11 14:05:47.639 I/chromium( 7941):     at m (file:///android_asset/www/js/ext/jquery.js:2:393)
03-11 14:05:47.639 I/chromium( 7941):     at processEditor (file:///android_asset/www/plugins/decision-tree/js/decision-tree.js:363:21)
03-11 14:05:47.639 I/chromium( 7941):     at Object._base.processEditor (file:///android_asset/www/js/records.js:1408:25)", source: file:///android_asset/www/cordova.js (1076)

Related to function: https://github.com/edina/fieldtrip-decision-tree/blob/0.3.9/src/www/js/decision-tree.js#L362

Agreed with Panos functionality is no longer needed and will be removed.
