### ISSUE TITLE
Tutorial 2: A way of overwriting/extending templates

### ISSUE THREAD

**Issue by panterz** [edina/fieldtrip-cobweb-project#123]
This tutorial should introduce a way of adding extra buttons or overwriting existing ones by using the Fieldtrip Open template system.

**Comment by panterz** [comment]
https://github.com/edina/fieldtrip-open/wiki/Tutorials

**Comment by gmh04** [comment]
what about https://github.com/edina/fieldtrip-open/wiki/Develop#templates

**Comment by panterz** [comment]
We need to update the documentation related to internationalization.

**Comment by rgamez** [comment]
Documentation updated:

https://github.com/edina/fieldtrip-open/wiki/Develop#internationalisation
