### ISSUE TITLE
Tutorial 5:  I need to release my apk.

### ISSUE THREAD

**Issue by panterz** [edina/fieldtrip-cobweb-project#126]

**Comment by panterz** [comment]
https://github.com/edina/fieldtrip-open/wiki/Tutorials

**Comment by gmh04** [comment]
what about instructions here https://github.com/edina/fieldtrip-open/wiki/Deploy#user-content-release

**Comment by panterz** [comment]
sort it then. Add the link on the tutorial and you are done :)

**Comment by panterz** [comment]
iOS instructions are needed.

**Comment by rgamez** [comment]
Instructions updated: https://github.com/edina/fieldtrip-open/wiki/Deploy#ios-1
