### ISSUE TITLE
Tapping the Layers name is not centering the map in the tiles

### ISSUE THREAD

**Issue by rgamez** [edina/fieldtrip-cobweb-project#131]
Download a layer, go to the map page and activate it, you'll notice that the map is zoomed and paned to the extent of the new layer, but if you move the map and try to deactivate/activate the layer again nothing happens, tapping the layer name (which should perform a similar action) triggers the following error in the console:

```
Uncaught TypeError: Object #<Object> has no method 'getLayerByName' 
```

**Comment by gmh04** [comment]
available in 0.2.5
