### ISSUE TITLE
 It was not possible to move the location pointer

### ISSUE THREAD

**Issue by rgamez** [edina/fieldtrip-cobweb-project#141]
From Penparcau co-design activity
> It was not possible to move the location pointer until perhaps half an hour in to the survey, but it was working well by the end, for the final couple of hours. Furthermore, the viewer is showing many of the observations as being from the Morrison's building. Is this just the nature of using a COBWEB device which does not have a SIM card to help with improving location?

**Comment by rgamez** [comment]
Related: https://github.com/edina/fieldtrip-gb/issues/94

**Comment by gmh04** [comment]
I can reproduce this going to save map page, displaying the save map preview and then creating an observation.  The paddle location is there initially in the observation preview but once you click on the map it appears to disappear.  Zooming the map out to view the whole of the OK show the paddle somewhere in England.
