### ISSUE TITLE
 Missing i18n texts for checkbox.other and radio.other

### ISSUE THREAD

**Issue by rgamez** [edina/fieldtrip-cobweb-project#148]
> I'm having issues with the 'other' option on the app. If I select other option on either multiple or single choice fields, there is a bit of text that says either 'checkbox.other' or 'radio.other'

**Comment by gmh04** [comment]
commit: https://github.com/edina/fieldtrip-open/commit/850d6e69b3c6870e99f0830efbcfd9ebec85fead
