### ISSUE TITLE
App unable to view uploaded mbiles uploaded by Survey Designer

### ISSUE THREAD

**Issue by gmh04** [edina/fieldtrip-cobweb-project#150]
Upload is saved to the features directory of the user, whereas the layer plugin fetches only layers stored in anonymous.

**Comment by gmh04** [comment]
@xmichael the code is clear, the mbtiles plugin uses the anonymous userid for fetching layers, see:

https://github.com/edina/fieldtrip-overlays/blob/0.3.4/src/www/js/overlays.js#L125
https://github.com/edina/fieldtrip-overlays/blob/0.3.4/src/www/js/overlays.js#L79-L84

So layers uploaded for a private survey would never have been available on the app.  The question is do I change this to use the users id?

**Comment by xmichael** [comment]
@gmh04 so everything works for public surveys right ?

**Comment by gmh04** [comment]
Will not do at this time.
