### ISSUE TITLE
fix custom attributes

### ISSUE THREAD

**Issue by xmichael** [edina/fieldtrip-cobweb-project#151]
Custom attributes are added on the Survey level in the SD by click the "Add Attribute" button.

Currently if you define, for example, two attribute: `One Key --> One Value` and `Another Key` --> `Another Value` the survey designer will skip the keys and only save the values in the survey JSON file as follows:

``` json
"extra":[{"value":"One Value"},{"value":"Another Value"}]
```

While it should have been:

``` json
"extra":[{"One Key":"One Value"},{"Another Key":"Another Value"}]
```

**Comment by gmh04** [comment]
This looks to have been fixed by: https://github.com/edina/survey-designer/commit/ae71016e61f3107e765e22b45724f8efd2c75efa.  I have tested this on a dev version and it works.  Which SD are you using?
