### ISSUE TITLE
Polygon Capture

### ISSUE THREAD

**Issue by panterz** [edina/fieldtrip-cobweb-project#41]
We need a polygon capture button of FTOpen.

**Comment by panterz** [comment]
Added a toolbar on preview page and moved the details to an info button. Needs evaluation from design aspect. 
TODO:
1. replace icons
2. make use of the record-type which is hidden in the form and display equivalent toolbar icons
3. in case of GPS time out use the bbox of the form if exists

**Comment by panterz** [comment]
I leave this issue open for updating the icons.

**Comment by panterz** [comment]
![screenshot_2015-03-02-16-44-12](https://cloud.githubusercontent.com/assets/70038/6445484/1eef2768-c0fc-11e4-9ca2-f327fba82260.png)

![spritesheet](https://cloud.githubusercontent.com/assets/70038/6445501/37544450-c0fc-11e4-9e2b-c701772c6e00.png)


Check the first image to see how I changed map capture page. I added an info button on the header and the icons of the 2nd image on the left side of the map. We probably need brigh color icons.

**Comment by panterz** [comment]
Need to get rid of the text "Drag pin to Reposition"

**Comment by gmh04** [comment]
I assume you mean if Polygon, BBox or Line is selected?  I wonder if the "Drag pin to Reposition" dialog should disappear after a few seconds?

**Comment by panterz** [comment]
@gmh04 yup it does now.

**Comment by panterz** [comment]
The style of the polygon needs to change.

**Comment by panterz** [comment]
if GPS timed out the change from polygon to marker is not displaying a marker.

**Comment by panterz** [comment]
fixed the issue with the timeout.

**Comment by panterz** [comment]
Updated the images for different types of geometries.

**Comment by panterz** [comment]
working now
