### ISSUE TITLE
Remove the map of the annotation page preview

### ISSUE THREAD

**Issue by rgamez** [edina/fieldtrip-cobweb-project#46]
For cobweb we need to capture information related to a Feature, not only a point as we have been doing, that feature can be a [polygon](edina/fieldtrip-cobweb-project#41), line a polyline, etc..

I find that the map in the annotation page preview rather small for both purposes, reviewing the data that you captured and navigating the map

For solving this I think that the action of capturing a feature should be a widget in the form that you explicitly click and displays a full page map where according to the type of feature enables the proper controls, for a point a paddle, for an area a polygon, etc.. we can also preserve the annotation page preview but just for previewing the annotation.

**Comment by gmh04** [comment]
Ruben, make sure this get talked about at the next meeting.

**Comment by panterz** [comment]
It has been implemented in a different way. There's a selection of options on the map preview page of geometries.
