### ISSUE TITLE
Make the default location configurable

### ISSUE THREAD

**Issue by rgamez** [edina/fieldtrip-cobweb-project#50]
> A minor issue what happens when the observer uses a device without GPS. In that case when the observation tries to save the user is free to pinpoint anywhere in the globe, especially if he is offline and has not cached the appropriate maps. In a first such attempt offline the cobweb map showed Wales, while we were in Greece.

**Comment by panterz** [comment]
default location is defined by globalization. If there's none then stay with the default one.
