### ISSUE TITLE
AT should enforce unique titles

### ISSUE THREAD

**Issue by xmichael** [edina/fieldtrip-cobweb-project#58]
The current COBWEB data format uses widget titles as property names (columns) in the database. We therefore need a unique title for each widget of the survey.

AT should enforce this when clicking "Save". It should:
 1 . Loop through all the titles and if a duplicate is found then issue an alert e.g.:
 `Duplicate title "Confidence in value?"`
 2. If not duplicates are found then save normally.

**Comment by panterz** [comment]
It's 1.5 year old. Is this still needed to be done?

**Comment by xmichael** [comment]
Not relevant -- it goes back to the days when people mistook flat schemas as illegal characters. We are not using flat schemas anymore.
