### ISSUE TITLE
Multiple image capture in the form

### ISSUE THREAD

**Issue by rgamez** [edina/fieldtrip-cobweb-project#78]
Let the user capture multiple images in a single form

**Comment by gmh04** [comment]
related?: https://github.com/edina/fieldtrip-gb/issues/126

**Comment by rgamez** [comment]
Not really, this one comes from a restriction in the authoring tool, if you try to add a second image capture button you get this message:

```
Feedback

You can only add one photo button once!
```

Allowing a second button probably would have some repercussions in the app.
