### ISSUE TITLE
Edit observations in the app

### ISSUE THREAD

**Issue by rgamez** [edina/fieldtrip-cobweb-project#81]
Add the possibility of editing observations in the app before being uploaded.

**Comment by gmh04** [comment]
related: https://github.com/edina/fieldtrip-gb/issues/172

**Comment by panterz** [comment]
I've added the editing functionality. At the moment it goes through the whole workflow, so the coordinates are updated with the GPS at the time of editing.

**Comment by gmh04** [comment]
Only records with points are editable.
