### ISSUE TITLE
Timeout during the polling won't return the user to the app

### ISSUE THREAD

**Issue by rgamez** [edina/fieldtrip-cobweb-project#85]
During the authentication if there is any problem with the polling, the child browser is not closed, leaving the user staring a white screen with a json response, in this case I was authenticated correctly because I could see the ```{"state": 1}``` in the json response but for an unkown reason the polling timed out.

```
Poll: https://dyfi.cobwebproject.eu/1.3/pcapi/auth/local pcapi.js:83
keyboard visible: 305 : 567 ui.js:187
keyboard visible: 345 : 567 ui.js:187
keyboard visible: 305 : 567 ui.js:187
keyboard visible: 345 : 567 ui.js:187
Problem polling api: timeout pcapi.js:105
    $.ajax.error pcapi.js:105
keyboard visible: 305 : 567 ui.js:187
keyboard visible: 345 : 567 ui.js:187
```

**Comment by benismobile** [comment]
Both Ian and Tom reported an issue (white screen of death) for a couple of FtGB users at the GeoForum event. .

**Comment by rgamez** [comment]
Premature closing, I did some tests throttling the connection and becomes almost impossible to do login with the 3 seconds timeout.
