### ISSUE TITLE
Way to add hardcoded editors

### ISSUE THREAD

**Issue by panterz** [edina/fieldtrip-cobweb-project#95]
In Opal there's a requirement to have a default form on the form which is this one:
http://www.opalexplorenature.org/sites/default/files/7/image/TREE%2016pp%20booklet.pdf

Any suggestions?
One way would be to have a folder called editors inside the project that is copied over when the app is compiled.

**Comment by rgamez** [comment]
I think @gmh04  did some work on this here edina/env-sys#3

**Comment by panterz** [comment]
Transfer the copy to the build task

**Comment by panterz** [comment]
I am closing this for the time being.
